language: ruby

rvm:
  - 2.2
  
script:
  - bundle install
  - bundle exec rake
  - bundle exec rake spec
  - bundle exec rake features 
  
notifications:
  email:
    on_success: never
    on_failure: never
